### PR TITLE
Eak folder errors

### PR DESCRIPTION
**Pull request by eakischuk**
### Project Management
Issue name:

Closes #

------------------------------------------------------------------------------
### Request Status
* [ ] Completed
* [ ] In progress

------------------------------------------------------------------------------
### Test coverage

* [ ] 100% Model Testing
* [ ] 100% Request Testing
* [ ] 100% Other Testing (Services/Poros/etc.)

If below 100%, what still needs testing:
- error raising within conditional block for createFolder not being hit by current testing

------------------------------------------------------------------------------
### Change Log

What I did:
- added error handling to all folder mutations; create, update, and delete

Things to consider:
- x

What needs to be refactored:
- x

What still needs help:
- x

### CODE REVIEW

**Comment by jamiejpace** [comment]
Looks good!

**Comment by jamiejpace** [comment]
For createUser, I added the raise GraphQL::ExecutionError, but I didn't add the rescue ActiveRecord::RecordInvalid. Do I need to add both? I guess I'm confused on that.

**Comment by eakischuk** [comment]
> For createUser, I added the raise GraphQL::ExecutionError, but I didn't add the rescue ActiveRecord::RecordInvalid. Do I need to add both? I guess I'm confused on that.

I don't think we need both in this context, but for a context where a certain data type is required (like trying to store a string for an integer type attribute) we would need to rescue from RecordInvalid as well

**Comment by jamiejpace** [comment]
> > For createUser, I added the raise GraphQL::ExecutionError, but I didn't add the rescue ActiveRecord::RecordInvalid. Do I need to add both? I guess I'm confused on that.
> 
> I don't think we need both in this context, but for a context where a certain data type is required (like trying to store a string for an integer type attribute) we would need to rescue from RecordInvalid as well

Great, thank you for clarifying this for me!

**Pull request merged**
